spring:
  port:
  datasource:
    username:
    password:
    url:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto:
  grpc:
    server:
      host:
      port:
  kafka:
    bootstrap-servers:
kafka:
  topic:
    bulk-discount:
variables:
  bulk-discount:
    send-all-after-start: true